CREATE TABLE uuevents (
  identifier varchar(255) PRIMARY KEY NOT NULL,
  issuedTime timestamp,
  producer varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  producerReferenceId varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  event_type varchar(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL
);

CREATE TABLE CAMEL_MESSAGEPROCESSED (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  processorName VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  messageId VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  createdAt TIMESTAMP,
  UNIQUE KEY `ix_key` (`processorName`, `messageId`)
);

CREATE TABLE POTENTIAL_MEMBERSHIP_EVENTS (
  id            BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  date          TIMESTAMP NOT NULL,
  pnr           VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  meType        VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  courseCode    VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin,
  reportCode    VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin,
  startSemester VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin,
  semester      VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin,
  origin        VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  origin2       VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin,
  processed     BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE MEMBERSHIP_EVENTS (
  id            BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  pmeId         BIGINT NOT NULL,
  date          TIMESTAMP NOT NULL,
  pnr           VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  meType        VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  courseCode    VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  reportCode    VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  startSemester VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  semester      VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  origin        VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  origin2       VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin,
  FOREIGN KEY (pmeId) REFERENCES POTENTIAL_MEMBERSHIP_EVENTS(id)
);

CREATE TABLE MEMBERSHIPS (
  id            BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  meId          BIGINT NOT NULL,
  date          TIMESTAMP NOT NULL,
  pnr           VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  courseCode    VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  reportCode    VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  startSemester VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  semester      VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  origin        VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin NOT NULL,
  origin2       VARCHAR(255) CHARACTER SET utf8 COLLATE utf8_bin,
  FOREIGN KEY (meId) REFERENCES MEMBERSHIP_EVENTS(id)
);
